### ISSUE TITLE
licenserequest for multipart books

### ISSUE THREAD

**Issue by mkb79** [omarroth/audible.cr#2]
Hi omarroth,

I noticed yesterday that a post to /1.0/content/{asin}/licenserequest failed with http error 404 (url not found).

After hours of search I found the solution in the official ios audible app. There I can‘t download the whole audiobook if it‘s a multipart book. I have to download every part separately.

If you want to get download urls for multipart books you have to figure out the asin for every part of the book. Best therefore is to make call GET /1.0/library/{parent_asin} with response_groups: relationships. In the json response body you get all children_asins. 

Now you can feed your licenserequest call with the children_asins. 

Greets

**Comment by omarroth** [comment]
Added some more info with 6738f446f5f1277100918cb67719bf28510f70f8.
