### ISSUE TITLE
Whispersync for voice

### ISSUE THREAD

**Issue by flo62134** [omarroth/audible.cr#6]
Hi!

Thanks a lot for the hard work on this!
I also am a big fan of Audible and Kindle. 
I tend to buy the Kindle and Audible versions of the same book. 

Although, whispersync for voice is not available in my country.
However, the books I buy definitely support Whispersync for voice.

I'm looking for a homemade way to synchronize my Kindle and Audible books.
Would your API be of any help to achieve my goal?

Thanks for your help!

**Comment by omarroth** [comment]
I expect so. Right now most development is happening in mkb79's repository: https://github.com/mkb79/Audible so I would recommend opening a new issue there. Cheers.
